secrets:
  - kmsKeyName: projects/$_PROJECT_ID/locations/global/keyRings/$_KEYRING/cryptoKeys/$_KEYNAME
    secretEnv:
      FIREBASE_TOKEN: $_TOKEN

steps:
  - name: 'gcr.io/$_PROJECT_ID/firebase'
    args: ['deploy']
    secretEnv: ['FIREBASE_TOKEN']
