secrets:
  - kmsKeyName: projects/$_PROJECT_ID/locations/global/keyRings/$_KEYRING/cryptoKeys/$_KEYNAME
    secretEnv:
      FIREBASE_TOKEN: CiQAM8BOv5N1wL8NZjk23HlVC8MC+VLclz+P9bYy4OPBLco+xHMSkAEAtluqk9CN5BCjylno99dNc4w/5FMJAu/beIuE5ARky4qCZ1IYsRnj83Z5/Jd8ynL2dUT26CZ6b3o+Otoz9L7seHQ2Ky2g1S1fyBd9PQj3v9mhpZiIRXf6OC6WvHA4cxTxHG5zpfbGmu8xaiBft+e4puEspr7eHha31xBOR58HGpAYthVaEpPEVZP3/ebuVEM=

steps:
  - name: 'gcr.io/$_PROJECT_ID/firebase'
    args: ['deploy']
    secretEnv: ['FIREBASE_TOKEN']
